apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicas
  labels:
    app: my-replicas
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: my-replicas
        image: nginx:alpine
